/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IUnipilotDeployer,
  IUnipilotDeployerInterface,
} from "../IUnipilotDeployer";

const _abi = [
  {
    inputs: [],
    name: "parameters",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUnipilotDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IUnipilotDeployerInterface {
    return new utils.Interface(_abi) as IUnipilotDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): IUnipilotDeployer {
    return new Contract(address, _abi, signerOrProvider) as IUnipilotDeployer;
  }
}
