/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUniStrategy, IUniStrategyInterface } from "../IUniStrategy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "int24",
        name: "oldBaseTicks",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newBaseTicks",
        type: "int24",
      },
    ],
    name: "BaseTicksUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldGovernance",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newGovernance",
        type: "address",
      },
    ],
    name: "GovernanceUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "int24",
        name: "oldDeviation",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newDeviation",
        type: "int24",
      },
    ],
    name: "MaxTwapDeviationUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "int24",
        name: "oldRangeTicks",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newRangeTicks",
        type: "int24",
      },
    ],
    name: "RangeTicksUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "int24",
        name: "oldMultiplier",
        type: "int24",
      },
      {
        indexed: false,
        internalType: "int24",
        name: "newMultiplier",
        type: "int24",
      },
    ],
    name: "ReadjustMultiplierUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "int24",
            name: "baseThreshold",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "rangeThreshold",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "maxTwapDeviation",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "readjustThreshold",
            type: "int24",
          },
          {
            internalType: "uint32",
            name: "twapDuration",
            type: "uint32",
          },
        ],
        indexed: false,
        internalType: "struct IUniStrategy.PoolStrategy",
        name: "oldStrategy",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "int24",
            name: "baseThreshold",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "rangeThreshold",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "maxTwapDeviation",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "readjustThreshold",
            type: "int24",
          },
          {
            internalType: "uint32",
            name: "twapDuration",
            type: "uint32",
          },
        ],
        indexed: false,
        internalType: "struct IUniStrategy.PoolStrategy",
        name: "newStrategy",
        type: "tuple",
      },
    ],
    name: "StrategyUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint32",
        name: "oldDuration",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "newDuration",
        type: "uint32",
      },
    ],
    name: "TwapDurationUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
    ],
    name: "getReadjustThreshold",
    outputs: [
      {
        internalType: "int24",
        name: "readjustThreshold",
        type: "int24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
    ],
    name: "getStrategy",
    outputs: [
      {
        components: [
          {
            internalType: "int24",
            name: "baseThreshold",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "rangeThreshold",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "maxTwapDeviation",
            type: "int24",
          },
          {
            internalType: "int24",
            name: "readjustThreshold",
            type: "int24",
          },
          {
            internalType: "uint32",
            name: "twapDuration",
            type: "uint32",
          },
        ],
        internalType: "struct IUniStrategy.PoolStrategy",
        name: "strategy",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
    ],
    name: "getTicks",
    outputs: [
      {
        internalType: "int24",
        name: "baseLower",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "baseUpper",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "bidLower",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "bidUpper",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "askLower",
        type: "int24",
      },
      {
        internalType: "int24",
        name: "askUpper",
        type: "int24",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
    ],
    name: "getTwap",
    outputs: [
      {
        internalType: "int24",
        name: "",
        type: "int24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUniStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IUniStrategyInterface {
    return new utils.Interface(_abi) as IUniStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): IUniStrategy {
    return new Contract(address, _abi, signerOrProvider) as IUniStrategy;
  }
}
