/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  PeripheryPayments,
  PeripheryPaymentsInterface,
} from "../PeripheryPayments";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

export class PeripheryPayments__factory {
  static readonly abi = _abi;
  static createInterface(): PeripheryPaymentsInterface {
    return new utils.Interface(_abi) as PeripheryPaymentsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PeripheryPayments {
    return new Contract(address, _abi, signerOrProvider) as PeripheryPayments;
  }
}
