/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { UnipilotMaths, UnipilotMathsInterface } from "../UnipilotMaths";

const _abi = [
  {
    inputs: [],
    name: "PRECISION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6070610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063aaf5eb68146038575b600080fd5b603e6050565b60408051918252519081900360200190f35b6ec097ce7bc90715b34b9f10000000008156fea164736f6c6343000706000a";

export class UnipilotMaths__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<UnipilotMaths> {
    return super.deploy(overrides || {}) as Promise<UnipilotMaths>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> },
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): UnipilotMaths {
    return super.attach(address) as UnipilotMaths;
  }
  connect(signer: Signer): UnipilotMaths__factory {
    return super.connect(signer) as UnipilotMaths__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UnipilotMathsInterface {
    return new utils.Interface(_abi) as UnipilotMathsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider,
  ): UnipilotMaths {
    return new Contract(address, _abi, signerOrProvider) as UnipilotMaths;
  }
}
