/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  UnipilotRouter,
  UnipilotRouterInterface,
} from "../UnipilotRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_unipilotFactory",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_vault",
        type: "address",
      },
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount1",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "uint256",
        name: "lpShares",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unipilotFactory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103673803806103678339818101604052602081101561003357600080fd5b5051600080546001600160a01b039092166001600160a01b0319909216919091179055610302806100656000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806320e8c5651461003b5780638b9c2c8014610089575b600080fd5b6100776004803603608081101561005157600080fd5b506001600160a01b038135811691602081013590911690604081013590606001356100ad565b60408051918252519081900360200190f35b6100916102e6565b604080516001600160a01b039092168252519081900360200190f35b60006001600160a01b038516158015906100cf57506001600160a01b03841615155b610105576040805162461bcd60e51b81526020600482015260026024820152614e4160f01b604482015290519081900360640190fd5b6000806000876001600160a01b0316637f98aa716040518163ffffffff1660e01b815260040160606040518083038186803b15801561014357600080fd5b505afa158015610157573d6000803e3d6000fd5b505050506040513d606081101561016d57600080fd5b508051602080830151604093840151600080548651637062590560e11b81526001600160a01b038088166004830152808616602483015262ffffff851660448301529751969a5093985091965094169263e0c4b20a92606480840193919291829003018186803b1580156101e057600080fd5b505afa1580156101f4573d6000803e3d6000fd5b505050506040513d602081101561020a57600080fd5b50516001600160a01b0316141561024e576040805162461bcd60e51b81526020600482015260036024820152624e564160e81b604482015290519081900360640190fd5b604080516320e8c56560e01b81523360048201526001600160a01b03898116602483015260448201899052606482018890529151918a16916320e8c565916084808201926020929091908290030181600087803b1580156102ae57600080fd5b505af11580156102c2573d6000803e3d6000fd5b505050506040513d60208110156102d857600080fd5b505198975050505050505050565b6000546001600160a01b03168156fea164736f6c6343000706000a";

export class UnipilotRouter__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    _unipilotFactory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<UnipilotRouter> {
    return super.deploy(
      _unipilotFactory,
      overrides || {}
    ) as Promise<UnipilotRouter>;
  }
  getDeployTransaction(
    _unipilotFactory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_unipilotFactory, overrides || {});
  }
  attach(address: string): UnipilotRouter {
    return super.attach(address) as UnipilotRouter;
  }
  connect(signer: Signer): UnipilotRouter__factory {
    return super.connect(signer) as UnipilotRouter__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UnipilotRouterInterface {
    return new utils.Interface(_abi) as UnipilotRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UnipilotRouter {
    return new Contract(address, _abi, signerOrProvider) as UnipilotRouter;
  }
}
