/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type PoolStrategyStruct = {
  baseThreshold: BigNumberish;
  rangeThreshold: BigNumberish;
  maxTwapDeviation: BigNumberish;
  readjustThreshold: BigNumberish;
  twapDuration: BigNumberish;
};

export type PoolStrategyStructOutput = [
  number,
  number,
  number,
  number,
  number,
] & {
  baseThreshold: number;
  rangeThreshold: number;
  maxTwapDeviation: number;
  readjustThreshold: number;
  twapDuration: number;
};

export interface UniStrategyInterface extends utils.Interface {
  functions: {
    "baseTicks()": FunctionFragment;
    "changeStrategy((int24,int24,int24,int24,uint32),address)": FunctionFragment;
    "getReadjustThreshold(address)": FunctionFragment;
    "getStrategy(address)": FunctionFragment;
    "getTicks(address)": FunctionFragment;
    "getTwap(address)": FunctionFragment;
    "governance()": FunctionFragment;
    "rangeTicks()": FunctionFragment;
    "setAllStrategies((int24,int24,int24,int24,uint32)[],address[])": FunctionFragment;
    "setBaseTicks(int24)": FunctionFragment;
    "setGovernance(address)": FunctionFragment;
    "setMaxTwapDeviation(int24)": FunctionFragment;
    "setPoolTwapDeviation(address[],int24[])": FunctionFragment;
    "setRangeTicks(int24)": FunctionFragment;
    "setReadjustMultiplier(int24)": FunctionFragment;
    "setTwapDuration(uint32)": FunctionFragment;
    "unipilot()": FunctionFragment;
    "updateUnipilotAddress(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "baseTicks", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "changeStrategy",
    values: [PoolStrategyStruct, string],
  ): string;
  encodeFunctionData(
    functionFragment: "getReadjustThreshold",
    values: [string],
  ): string;
  encodeFunctionData(functionFragment: "getStrategy", values: [string]): string;
  encodeFunctionData(functionFragment: "getTicks", values: [string]): string;
  encodeFunctionData(functionFragment: "getTwap", values: [string]): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "rangeTicks",
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: "setAllStrategies",
    values: [PoolStrategyStruct[], string[]],
  ): string;
  encodeFunctionData(
    functionFragment: "setBaseTicks",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTwapDeviation",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolTwapDeviation",
    values: [string[], BigNumberish[]],
  ): string;
  encodeFunctionData(
    functionFragment: "setRangeTicks",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setReadjustMultiplier",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: "setTwapDuration",
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: "unipilot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateUnipilotAddress",
    values: [string],
  ): string;

  decodeFunctionResult(functionFragment: "baseTicks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeStrategy",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReadjustThreshold",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrategy",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "getTicks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rangeTicks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllStrategies",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBaseTicks",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTwapDeviation",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolTwapDeviation",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRangeTicks",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReadjustMultiplier",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTwapDuration",
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: "unipilot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateUnipilotAddress",
    data: BytesLike,
  ): Result;

  events: {
    "BaseTicksUpdated(int24,int24)": EventFragment;
    "GovernanceUpdated(address,address)": EventFragment;
    "MaxTwapDeviationUpdated(int24,int24)": EventFragment;
    "RangeTicksUpdated(int24,int24)": EventFragment;
    "ReadjustMultiplierUpdated(int24,int24)": EventFragment;
    "StrategyUpdated(tuple,tuple)": EventFragment;
    "TwapDurationUpdated(uint32,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BaseTicksUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernanceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MaxTwapDeviationUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RangeTicksUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReadjustMultiplierUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StrategyUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TwapDurationUpdated"): EventFragment;
}

export type BaseTicksUpdatedEvent = TypedEvent<
  [number, number],
  { oldBaseTicks: number; newBaseTicks: number }
>;

export type BaseTicksUpdatedEventFilter =
  TypedEventFilter<BaseTicksUpdatedEvent>;

export type GovernanceUpdatedEvent = TypedEvent<
  [string, string],
  { oldGovernance: string; newGovernance: string }
>;

export type GovernanceUpdatedEventFilter =
  TypedEventFilter<GovernanceUpdatedEvent>;

export type MaxTwapDeviationUpdatedEvent = TypedEvent<
  [number, number],
  { oldDeviation: number; newDeviation: number }
>;

export type MaxTwapDeviationUpdatedEventFilter =
  TypedEventFilter<MaxTwapDeviationUpdatedEvent>;

export type RangeTicksUpdatedEvent = TypedEvent<
  [number, number],
  { oldRangeTicks: number; newRangeTicks: number }
>;

export type RangeTicksUpdatedEventFilter =
  TypedEventFilter<RangeTicksUpdatedEvent>;

export type ReadjustMultiplierUpdatedEvent = TypedEvent<
  [number, number],
  { oldMultiplier: number; newMultiplier: number }
>;

export type ReadjustMultiplierUpdatedEventFilter =
  TypedEventFilter<ReadjustMultiplierUpdatedEvent>;

export type StrategyUpdatedEvent = TypedEvent<
  [PoolStrategyStructOutput, PoolStrategyStructOutput],
  {
    oldStrategy: PoolStrategyStructOutput;
    newStrategy: PoolStrategyStructOutput;
  }
>;

export type StrategyUpdatedEventFilter = TypedEventFilter<StrategyUpdatedEvent>;

export type TwapDurationUpdatedEvent = TypedEvent<
  [number, number],
  { oldDuration: number; newDuration: number }
>;

export type TwapDurationUpdatedEventFilter =
  TypedEventFilter<TwapDurationUpdatedEvent>;

export interface UniStrategy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniStrategyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    baseTicks(overrides?: CallOverrides): Promise<[number]>;

    changeStrategy(
      params: PoolStrategyStruct,
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<[number] & { readjustThreshold: number }>;

    getStrategy(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<
      [PoolStrategyStructOutput] & { strategy: PoolStrategyStructOutput }
    >;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    getTwap(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<[number] & { twap: number }>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    rangeTicks(overrides?: CallOverrides): Promise<[number]>;

    setAllStrategies(
      params: PoolStrategyStruct[],
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setBaseTicks(
      _baseTicks: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setMaxTwapDeviation(
      _twapDeviation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setPoolTwapDeviation(
      _pools: string[],
      _twapDeviations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setRangeTicks(
      _rangeTicks: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setReadjustMultiplier(
      _readjustMultipier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    setTwapDuration(
      _twapDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    unipilot(overrides?: CallOverrides): Promise<[string]>;

    updateUnipilotAddress(
      _unipilot: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;
  };

  baseTicks(overrides?: CallOverrides): Promise<number>;

  changeStrategy(
    params: PoolStrategyStruct,
    _pool: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  getReadjustThreshold(
    _pool: string,
    overrides?: CallOverrides,
  ): Promise<number>;

  getStrategy(
    _pool: string,
    overrides?: CallOverrides,
  ): Promise<PoolStrategyStructOutput>;

  getTicks(
    _pool: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  getTwap(_pool: string, overrides?: CallOverrides): Promise<number>;

  governance(overrides?: CallOverrides): Promise<string>;

  rangeTicks(overrides?: CallOverrides): Promise<number>;

  setAllStrategies(
    params: PoolStrategyStruct[],
    pools: string[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setBaseTicks(
    _baseTicks: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setGovernance(
    _governance: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setMaxTwapDeviation(
    _twapDeviation: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setPoolTwapDeviation(
    _pools: string[],
    _twapDeviations: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setRangeTicks(
    _rangeTicks: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setReadjustMultiplier(
    _readjustMultipier: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  setTwapDuration(
    _twapDuration: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  unipilot(overrides?: CallOverrides): Promise<string>;

  updateUnipilotAddress(
    _unipilot: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  callStatic: {
    baseTicks(overrides?: CallOverrides): Promise<number>;

    changeStrategy(
      params: PoolStrategyStruct,
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<number>;

    getStrategy(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<PoolStrategyStructOutput>;

    getTicks(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<
      [number, number, number, number, number, number] & {
        baseLower: number;
        baseUpper: number;
        bidLower: number;
        bidUpper: number;
        askLower: number;
        askUpper: number;
      }
    >;

    getTwap(_pool: string, overrides?: CallOverrides): Promise<number>;

    governance(overrides?: CallOverrides): Promise<string>;

    rangeTicks(overrides?: CallOverrides): Promise<number>;

    setAllStrategies(
      params: PoolStrategyStruct[],
      pools: string[],
      overrides?: CallOverrides,
    ): Promise<void>;

    setBaseTicks(
      _baseTicks: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    setGovernance(
      _governance: string,
      overrides?: CallOverrides,
    ): Promise<void>;

    setMaxTwapDeviation(
      _twapDeviation: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    setPoolTwapDeviation(
      _pools: string[],
      _twapDeviations: BigNumberish[],
      overrides?: CallOverrides,
    ): Promise<void>;

    setRangeTicks(
      _rangeTicks: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    setReadjustMultiplier(
      _readjustMultipier: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    setTwapDuration(
      _twapDuration: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<void>;

    unipilot(overrides?: CallOverrides): Promise<string>;

    updateUnipilotAddress(
      _unipilot: string,
      overrides?: CallOverrides,
    ): Promise<void>;
  };

  filters: {
    "BaseTicksUpdated(int24,int24)"(
      oldBaseTicks?: null,
      newBaseTicks?: null,
    ): BaseTicksUpdatedEventFilter;
    BaseTicksUpdated(
      oldBaseTicks?: null,
      newBaseTicks?: null,
    ): BaseTicksUpdatedEventFilter;

    "GovernanceUpdated(address,address)"(
      oldGovernance?: null,
      newGovernance?: null,
    ): GovernanceUpdatedEventFilter;
    GovernanceUpdated(
      oldGovernance?: null,
      newGovernance?: null,
    ): GovernanceUpdatedEventFilter;

    "MaxTwapDeviationUpdated(int24,int24)"(
      oldDeviation?: null,
      newDeviation?: null,
    ): MaxTwapDeviationUpdatedEventFilter;
    MaxTwapDeviationUpdated(
      oldDeviation?: null,
      newDeviation?: null,
    ): MaxTwapDeviationUpdatedEventFilter;

    "RangeTicksUpdated(int24,int24)"(
      oldRangeTicks?: null,
      newRangeTicks?: null,
    ): RangeTicksUpdatedEventFilter;
    RangeTicksUpdated(
      oldRangeTicks?: null,
      newRangeTicks?: null,
    ): RangeTicksUpdatedEventFilter;

    "ReadjustMultiplierUpdated(int24,int24)"(
      oldMultiplier?: null,
      newMultiplier?: null,
    ): ReadjustMultiplierUpdatedEventFilter;
    ReadjustMultiplierUpdated(
      oldMultiplier?: null,
      newMultiplier?: null,
    ): ReadjustMultiplierUpdatedEventFilter;

    "StrategyUpdated(tuple,tuple)"(
      oldStrategy?: null,
      newStrategy?: null,
    ): StrategyUpdatedEventFilter;
    StrategyUpdated(
      oldStrategy?: null,
      newStrategy?: null,
    ): StrategyUpdatedEventFilter;

    "TwapDurationUpdated(uint32,uint32)"(
      oldDuration?: null,
      newDuration?: null,
    ): TwapDurationUpdatedEventFilter;
    TwapDurationUpdated(
      oldDuration?: null,
      newDuration?: null,
    ): TwapDurationUpdatedEventFilter;
  };

  estimateGas: {
    baseTicks(overrides?: CallOverrides): Promise<BigNumber>;

    changeStrategy(
      params: PoolStrategyStruct,
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    getStrategy(_pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    getTwap(_pool: string, overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    rangeTicks(overrides?: CallOverrides): Promise<BigNumber>;

    setAllStrategies(
      params: PoolStrategyStruct[],
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setBaseTicks(
      _baseTicks: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setMaxTwapDeviation(
      _twapDeviation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setPoolTwapDeviation(
      _pools: string[],
      _twapDeviations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setRangeTicks(
      _rangeTicks: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setReadjustMultiplier(
      _readjustMultipier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    setTwapDuration(
      _twapDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    unipilot(overrides?: CallOverrides): Promise<BigNumber>;

    updateUnipilotAddress(
      _unipilot: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    baseTicks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeStrategy(
      params: PoolStrategyStruct,
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    getReadjustThreshold(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getStrategy(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    getTicks(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    getTwap(
      _pool: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    rangeTicks(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAllStrategies(
      params: PoolStrategyStruct[],
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setBaseTicks(
      _baseTicks: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setMaxTwapDeviation(
      _twapDeviation: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setPoolTwapDeviation(
      _pools: string[],
      _twapDeviations: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setRangeTicks(
      _rangeTicks: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setReadjustMultiplier(
      _readjustMultipier: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    setTwapDuration(
      _twapDuration: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    unipilot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateUnipilotAddress(
      _unipilot: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;
  };
}
